FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN swag init

RUN go build -o bin/mini-ticket

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/bin/mini-ticket .

EXPOSE 8080

CMD ["./mini-ticket"]