basePath: /api
definitions:
  models.CreateUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  models.CreateUserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Helpdesk API
  title: Mini Ticket API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Creates a new user in the system
      parameters:
      - description: User payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.CreateUserResponse'
      summary: Create a user
      tags:
      - users
swagger: "2.0"
